@startmindmap mapasite
+[#MediumPurple] Inicial
++ Institucional
+++[#Aquamarine] Gestores
+++[#Aquamarine] Organograma
+++ Competências
+++[#Orange] Legislação
+++ Relatório de Acompanhamento de Projetos e Execução de Obras Públicas
+++ Relatório de Gestão Fiscal
+++ Relatório Resumido de Execução Orçamentária
+++[#Orange] Horário de Atendimento
+++[#Orange] Endereços e Contatos
+++[#plum] Site Institucional
++ O que estamos fazendo
+++[#Orange] Lista das ações e programas
+++[#Orange] Carta de Serviços
+++[#Orange] Programas Financiados
+++ Participação do orçamento da prefeitura
++ Convênios 
+++ Informações
+++[#plum] Dados do SINCOV
++ Participação Social
+++  Ouvidoria
+++  Audiências e Consultas Públicas
+++  Consórcios e Órgãos Colegiados
+++[#Orange]  Outras ações
+++  Serviço de Informações ao Cidadão
++ Auditorias
+++[#plum]  Consulta processos do TCE-RS 
+++  Relatórios de Auditoria Interna
+++  Controle Interno
+++  Controladoria-Geral do Município
++ Licitações e Contratos
+++[#plum]  Dados do LICITACON
+++[#Aquamarine]  Editais
+++[#Aquamarine]  Realizadas
+++[#Aquamarine]  Em andamento 
++ Servidores
+++[#Aquamarine]  Dados 
+++[#Aquamarine]  Diárias e Passagens
+++  Treinamentos Realizados/Eventos
++ Receitas e Despesas
+++[#Aquamarine]  Receitas
+++[#Aquamarine]  Despesas
+++[#Aquamarine]  Renúncia de Receitas
+++[#Aquamarine]  Prestação de Contas
+++[#Aquamarine]  Lei de Responsabilidade Fiscal
--[#Orange] Ajuda
--[#Aquamarine] COVID
--[#Orange] Política de Privacidade
--[#Orange] Termos de uso
-- Informações Classificadas
--[#Aquamarine] Glossário
-- Dados Abertos
--[#Tomato] Autenticação/Login
--[#Aquamarine] Consultas Salvas
--[#Aquamarine] Minhas notificações
@endmindmap
